### ISSUE TITLE
fitness function

### ISSUE THREAD

**Issue by kaushik94** [kaushik94/AngryBirds#7]
create a fitness value for each trajectory ie how many blocks/ pigs it passes through.

**Comment by kaushik94** [comment]
[Qualitative Spatial Representation and Reasoning in Angry Birds](http://users.cecs.anu.edu.au/~jrenz/papers/Zhang-Renz-KR14.pdf)

**Comment by altaiezior** [comment]
Yes Kaushik, I too wanted to add this paper here.
Also checkout the paper for Datalabs, the winners..
They used those stratergies we had planned, like constructing the structures and identifying them as too or wide, hitting the spherical or special structure and TNTs.
